### ISSUE TITLE
Administrator manual (translations etc.)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#38]
[0] has been updated in order to appear and navigate similar to what is described in #33.

## Tasks

Remaining tasks include check links in related templates, and if necessary add the appropriate template or create a redirect if the content is outdated.

- [ ] Template:SMW admin TOC (de)
- [ ] Template:SMW admin TOC (ja)
- [ ] Template:SMW admin TOC (ru)
- [ ] Template:SMW admin TOC (zh-hans)
- [ ] Template:Table des matières admin SMW

[0] https://www.semantic-mediawiki.org/wiki/Help:Administrator_manual
